# Amazon Sales Analysis Using Pandas

## Project Overview

This project analyzes Amazon sales data to understand sales performance, customer demand, order cancellations, and revenue trends. The dataset contains order information such as product category, order status, fulfillment method, shipping location, order date, and revenue.

The goal of this analysis is to transform raw sales data into meaningful business insights that can help decision-makers improve sales performance and reduce revenue loss.

## Business Questions

The following business questions were investigated:

1. What is the total revenue generated?
2. What percentage of orders are cancelled?
3. Which fulfillment method is used most frequently?
4. Which product category receives the most orders?
5. Which product category generates the highest revenue?
6. Which category has the highest average order value?
7. Which product size is ordered most frequently?
8. Which size generates the highest revenue?
9. Which states generate the most orders?
10. Which states generate the highest revenue?
11. Which cities generate the most orders?
12. Which cities generate the highest revenue?
13. Which month generates the highest revenue?
14. Which month generates the lowest revenue?
15. How does revenue change over time?
16. What is the average order value?
17. What is the revenue contribution of each category?
18. Which category has the highest cancellation rate?
19. How much revenue is lost due to cancelled orders?

## Tools Used

* Python
* Pandas
* Jupyter Notebook

## Expected Outcome

The analysis helps identify top-performing products, high-revenue regions, cancellation patterns, customer purchasing behavior, and potential revenue losses. These insights can support better inventory planning, marketing strategies, and operational decision-making.

In [1]:
import pandas as pd

df = pd.read_csv("Amazon Sale Report.csv")

df

C:\Users\pradip\AppData\Local\Temp\ipykernel_7660\1740072883.py:3: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Amazon Sale Report.csv")

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,...,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,promotion-ids,B2B,fulfilled-by,Unnamed: 22
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,...,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,NaN,False,Easy Ship,NaN
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,...,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,Amazon PLCC Free-Financing Universal Merchant ...,False,Easy Ship,NaN
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,...,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,True,NaN,NaN
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,...,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,NaN,False,Easy Ship,NaN
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,...,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,NaN,False,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,...,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,NaN,False,NaN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,...,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,...,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,NaN,False,NaN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,...,INR,1199.00,Halol,Gujarat,389350.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,...,INR,696.00,Raipur,CHHATTISGARH,492014.0,IN,IN Core Free Shipping 2015/04/08 23-48-5-108,False,NaN,False

In [2]:
df.shape

(128975, 24)

In [3]:
df.columns.tolist()

['index',
 'Order ID',
 'Date',
 'Status',
 'Fulfilment',
 'Sales Channel ',
 'ship-service-level',
 'Style',
 'SKU',
 'Category',
 'Size',
 'ASIN',
 'Courier Status',
 'Qty',
 'currency',
 'Amount',
 'ship-city',
 'ship-state',
 'ship-postal-code',
 'ship-country',
 'promotion-ids',
 'B2B',
 'fulfilled-by',
 'Unnamed: 22']

In [4]:
df.describe()

               index            Qty         Amount  ship-postal-code
count  128975.000000  128975.000000  121180.000000     128942.000000
mean    64487.000000       0.904431     648.561465     463966.236509
std     37232.019822       0.313354     281.211687     191476.764941
min         0.000000       0.000000       0.000000     110001.000000
25%     32243.500000       1.000000     449.000000     382421.000000
50%     64487.000000       1.000000     605.000000     500033.000000
75%     96730.500000       1.000000     788.000000     600024.000000
max    128974.000000      15.000000    5584.000000     989898.000000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 24 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   index               128975 non-null  int64
 1   Order ID            128975 non-null  object
 2   Date                128975 non-null  object
 3   Status              128975 non-null  object
 4   Fulfilment          128975 non-null  object
 5   Sales Channel       128975 non-null  object
 6   ship-service-level  128975 non-null  object
 7   Style               128975 non-null  object
 8   SKU                 128975 non-null  object
 9   Category            128975 non-null  object
 10  Size                128975 non-null  object
 11  ASIN                128975 non-null  object
 12  Courier Status      122103 non-null  object
 13  Qty                 128975 non-null  int64
 14  currency            121180 non-null  object
 15  Amount              121180 non-null  float64
 16  ship-city           128942 non-null  object
 17  ship-state          128942 non-null  object
 18  ship-postal-code    128942 non-null  float64
 19  ship-country        128942 non-null  object
 20  promotion-ids       79822 non-null   object
 21  B2B                 128975 non-null  bool
 22  fulfilled-by        39277 non-null   object
 23  Unnamed: 22         79925 non-null   object
dtypes: bool(1), float64(2), int64(2), object(19)
memory usage: 22.8+ MB

In [6]:
df.isnull().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

In [7]:
df.drop(["promotion-ids","fulfilled-by","Unnamed: 22","Courier Status"], axis=1,inplace=True)

In [8]:
df

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,False
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,B098112V2V,1,INR,517.00,HYDERABAD,TELANGANA,500013.0,IN,False
128971,128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,B09VC6KHX8,1,INR,999.00,GURUGRAM,HARYANA,122004.0,IN,False
128972,128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,B0982YZ51B,1,INR,690.00,HYDERABAD,TELANGANA,500049.0,IN,False
128973,128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,B0894Y2NJQ,1,INR,1199.00,Halol,Gujarat,389350.0,IN,False
128974,128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,B0894X27FC,1,INR,696.00,Raipur,CHHATTISGARH,492014.0,IN,False

In [9]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False
1,1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,False
2,2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True
3,3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False
4,4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df["ship-state"] = df["ship-state"].str.upper()

In [12]:
df["ship-state"].value_counts()

ship-state
MAHARASHTRA               22260
KARNATAKA                 17326
TAMIL NADU                11483
TELANGANA                 11330
UTTAR PRADESH             10638
DELHI                      6967
KERALA                     6585
WEST BENGAL                5963
ANDHRA PRADESH             5430
GUJARAT                    4489
HARYANA                    4415
RAJASTHAN                  2711
MADHYA PRADESH             2529
ODISHA                     2136
BIHAR                      2114
PUNJAB                     1917
ASSAM                      1663
UTTARAKHAND                1553
JHARKHAND                  1456
GOA                        1137
CHHATTISGARH                909
HIMACHAL PRADESH            788
JAMMU & KASHMIR             702
PUDUCHERRY                  350
CHANDIGARH                  333
MANIPUR                     316
ANDAMAN & NICOBAR           257
MEGHALAYA                   207
SIKKIM                      205
NAGALAND                    185
TRIPURA                     151
ARUNACHAL PRADESH           146
NEW DELHI                    81
MIZORAM                      76
DADRA AND NAGAR              70
LADAKH                       43
LAKSHADWEEP                   4
RAJSHTHAN                     3
ORISSA                        3
NL                            2
RJ                            2
RAJSTHAN                      2
PUNJAB/MOHALI/ZIRAKPUR        1
PB                            1
APO                           1
AR                            1
PONDICHERRY                   1
Name: count, dtype: int64

In [13]:
state_mapping = {
    "RAJSHTHAN": "RAJASTHAN",
    "RAJSTHAN": "RAJASTHAN",
    "RJ": "RAJASTHAN",
    "ORISSA": "ODISHA",
    "PB": "PUNJAB",
    "NEW DELHI": "DELHI",
    "PONDICHERRY": "PUDUCHERRY",
    "PUNJAB/MOHALI/ZIRAKPUR": "PUNJAB"
}

df["ship-state"] = df["ship-state"].replace(state_mapping)

In [14]:
df["ship-state"].value_counts()

ship-state
MAHARASHTRA           22260
KARNATAKA             17326
TAMIL NADU            11483
TELANGANA             11330
UTTAR PRADESH         10638
DELHI                  7048
KERALA                 6585
WEST BENGAL            5963
ANDHRA PRADESH         5430
GUJARAT                4489
HARYANA                4415
RAJASTHAN              2718
MADHYA PRADESH         2529
ODISHA                 2139
BIHAR                  2114
PUNJAB                 1919
ASSAM                  1663
UTTARAKHAND            1553
JHARKHAND              1456
GOA                    1137
CHHATTISGARH            909
HIMACHAL PRADESH        788
JAMMU & KASHMIR         702
PUDUCHERRY              351
CHANDIGARH              333
MANIPUR                 316
ANDAMAN & NICOBAR       257
MEGHALAYA               207
SIKKIM                  205
NAGALAND                185
TRIPURA                 151
ARUNACHAL PRADESH       146
MIZORAM                  76
DADRA AND NAGAR          70
LADAKH                   43
LAKSHADWEEP               4
NL                        2
APO                       1
AR                        1
Name: count, dtype: int64

In [15]:
df[df["Amount"].isnull()]

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,3XL,B08L91ZZXN,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,False
29,29,404-5933402-8801952,04-30-22,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,3XL,B07JG3CND8,0,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,False
65,65,171-4137548-0481151,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,XXL,B082W8RWN1,0,NaN,NaN,Dahod,GUJARAT,389151.0,IN,False
84,84,403-9950518-0349133,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,M,B08WPR5MCB,0,NaN,NaN,HYDERABAD,TELANGANA,500072.0,IN,False
95,95,405-9112089-3379536,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-L,kurta,L,B081WSCKPQ,0,NaN,NaN,PUNE,MAHARASHTRA,411046.0,IN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128903,128903,406-3923120-4345139,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3801,JNE3801-KR-M,kurta,M,B09SDZ4FH9,0,NaN,NaN,ANANTAPUR,ANDHRA PRADESH,515001.0,IN,False
128907,128907,403-6757403-6097100,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,NW014,NW014-ST-SR-XXXL,Set,3XL,B0928ZT74Y,0,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,IN,False
128908,128908,403-6757403-6097100,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,NW007,NW007-ST-CP-XXXL,Set,3XL,B0928YCMQP,0,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,IN,False
128958,128958,408-9513596-4393945,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,SET058,SET058-KR-NP-L,Set,L,B07R487XRD,0,NaN,NaN,Bengaluru,KARNATAKA,560037.0,IN,False
128967,128967,404-5182288-1653947,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3638,JNE3638-KR-XS,kurta,XS,B09814Q3QH,0,NaN,NaN,Kolkata,WEST BENGAL,700040.0,IN,False

In [16]:
(df["Amount"]==0).sum()

np.int64(2343)

In [17]:
df[df["Amount"].isnull()]["Status"].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [18]:
cancel_null=df[(df["Amount"].isnull()) & (df["Status"] == "Cancelled")]

In [19]:
cancel_null

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
8,8,407-5443024-5233168,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,3XL,B08L91ZZXN,0,NaN,NaN,HYDERABAD,TELANGANA,500008.0,IN,False
29,29,404-5933402-8801952,04-30-22,Cancelled,Merchant,Amazon.in,Standard,JNE2132,JNE2132-KR-398-XXXL,kurta,3XL,B07JG3CND8,0,NaN,NaN,GUWAHATI,ASSAM,781003.0,IN,False
65,65,171-4137548-0481151,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3373,JNE3373-KR-XXL,kurta,XXL,B082W8RWN1,0,NaN,NaN,Dahod,GUJARAT,389151.0,IN,False
84,84,403-9950518-0349133,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3510,JNE3510-KR-M,kurta,M,B08WPR5MCB,0,NaN,NaN,HYDERABAD,TELANGANA,500072.0,IN,False
95,95,405-9112089-3379536,04-30-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3405,JNE3405-KR-L,kurta,L,B081WSCKPQ,0,NaN,NaN,PUNE,MAHARASHTRA,411046.0,IN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128903,128903,406-3923120-4345139,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3801,JNE3801-KR-M,kurta,M,B09SDZ4FH9,0,NaN,NaN,ANANTAPUR,ANDHRA PRADESH,515001.0,IN,False
128907,128907,403-6757403-6097100,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,NW014,NW014-ST-SR-XXXL,Set,3XL,B0928ZT74Y,0,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,IN,False
128908,128908,403-6757403-6097100,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,NW007,NW007-ST-CP-XXXL,Set,3XL,B0928YCMQP,0,NaN,NaN,GREATER NOIDA,UTTAR PRADESH,201306.0,IN,False
128958,128958,408-9513596-4393945,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,SET058,SET058-KR-NP-L,Set,L,B07R487XRD,0,NaN,NaN,Bengaluru,KARNATAKA,560037.0,IN,False
128967,128967,404-5182288-1653947,05-31-22,Cancelled,Amazon,Amazon.in,Expedited,JNE3638,JNE3638-KR-XS,kurta,XS,B09814Q3QH,0,NaN,NaN,Kolkata,WEST BENGAL,700040.0,IN,False

In [20]:
df.loc[cancel_null.index,"Amount"]=0

In [21]:
not_cancel_null=df[(df["Amount"].isnull()) & (df["Status"] != "Cancelled")]

In [22]:
not_cancel_null["Amount"]

937      NaN
1057     NaN
1615     NaN
1989     NaN
2424     NaN
          ..
124616   NaN
124617   NaN
124619   NaN
124621   NaN
128085   NaN
Name: Amount, Length: 229, dtype: float64

In [23]:
median_amount = df["Amount"].median()

In [24]:
median_amount

587.0

In [25]:
df.loc[not_cancel_null.index,"Amount"]=median_amount

In [26]:
df["Amount"].isnull().sum()

np.int64(0)

In [27]:
df["Status"].value_counts()

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [28]:
df["Category"].value_counts()

Category
Set              50284
kurta            49877
Western Dress    15500
Top              10622
Ethnic Dress      1159
Blouse             926
Bottom             440
Saree              164
Dupatta              3
Name: count, dtype: int64

In [29]:
df["ship-city"].value_counts()

ship-city
BENGALURU                                      11217
HYDERABAD                                       8074
MUMBAI                                          6126
NEW DELHI                                       5795
CHENNAI                                         5421
                                               ...
Khandavalli, peravali mandal, west godavari        1
Bhayander west                                     1
JAKHALMANDI                                        1
Arariya                                            1
Halol                                              1
Name: count, Length: 8955, dtype: int64

In [30]:
higest_category_revenue = df.groupby("Category")["Amount"].sum()

In [31]:
higest_category_revenue.sort_values(ascending=False)

Category
Set              39265172.03
kurta            21358246.70
Western Dress    11221355.69
Top               5353662.30
Ethnic Dress       791804.66
Blouse             460756.18
Bottom             151254.98
Saree              123933.76
Dupatta               915.00
Name: Amount, dtype: float64

In [32]:
higest_state_revenue=df.groupby("ship-state")["Amount"].sum()

In [33]:
higest_state_revenue.sort_values(ascending=False)

ship-state
MAHARASHTRA           13349035.14
KARNATAKA             10484049.37
TELANGANA              6920724.65
UTTAR PRADESH          6819577.08
TAMIL NADU             6522694.11
DELHI                  4395870.41
KERALA                 3831988.58
WEST BENGAL            3510815.44
ANDHRA PRADESH         3225114.72
HARYANA                2885027.99
GUJARAT                2802026.82
RAJASTHAN              1765827.16
MADHYA PRADESH         1592382.98
BIHAR                  1416200.32
ODISHA                 1387546.39
PUNJAB                 1212840.84
ASSAM                  1019310.20
UTTARAKHAND             975317.55
JHARKHAND               920262.21
GOA                     639446.85
CHHATTISGARH            570485.83
HIMACHAL PRADESH        503364.51
JAMMU & KASHMIR         456932.74
MANIPUR                 213981.99
CHANDIGARH              212914.67
PUDUCHERRY              192573.24
ANDAMAN & NICOBAR       158723.62
NAGALAND                144094.67
SIKKIM                  140828.66
MEGHALAYA               119871.81
ARUNACHAL PRADESH        97772.00
TRIPURA                  92548.40
DADRA AND NAGAR          43312.92
MIZORAM                  41948.71
LADAKH                   38388.43
LAKSHADWEEP               3175.29
NL                         961.00
AR                         493.00
APO                          0.00
Name: Amount, dtype: float64

In [34]:
average_by_category=df.groupby("Category")["Amount"].mean()

In [35]:
average_by_category.sort_values(ascending=False)

Category
Set              780.868110
Saree            755.693659
Western Dress    723.958432
Ethnic Dress     683.179172
Top              504.016409
Blouse           497.576868
kurta            428.218351
Bottom           343.761318
Dupatta          305.000000
Name: Amount, dtype: float64

In [36]:
df["Date"] = pd.to_datetime(df["Date"])

C:\Users\pradip\AppData\Local\Temp\ipykernel_7660\936118274.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Date"] = pd.to_datetime(df["Date"])

In [37]:
monthly_sales = df.groupby(df["Date"].dt.strftime("%B"))["Amount"].sum()

In [38]:
monthly_sales.sort_values(ascending=False)

Date
April    28892125.32
May      26268740.75
June     23463964.38
March      102270.85
Name: Amount, dtype: float64

In [39]:
monthly_sales.sort_values()

Date
March      102270.85
June     23463964.38
May      26268740.75
April    28892125.32
Name: Amount, dtype: float64

In [40]:
revenue_overtime = df.groupby(df["Date"].dt.to_period("M"))["Amount"].sum()

In [41]:
revenue_overtime.sort_values()

Date
2022-03      102270.85
2022-06    23463964.38
2022-05    26268740.75
2022-04    28892125.32
Freq: M, Name: Amount, dtype: float64

In [42]:
df["Size"].value_counts()

Size
M       22711
L       22132
XL      20876
XXL     18096
S       17090
3XL     14816
XS      11161
6XL       738
5XL       550
4XL       427
Free      378
Name: count, dtype: int64

In [43]:
df.columns.tolist

<bound method IndexOpsMixin.tolist of Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Qty',
       'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code',
       'ship-country', 'B2B'],
      dtype='object')>

In [44]:
higest_revenue_size = df.groupby("Size")["Amount"].sum()

In [45]:
higest_revenue_size.sort_values(ascending = False)

Size
M       13928473.37
L       13258366.19
XL      12487271.86
S       10653277.18
XXL     10650376.45
3XL      9168300.68
XS       7035289.20
6XL       577423.33
5XL       426330.63
4XL       334451.64
Free      207540.77
Name: Amount, dtype: float64

In [46]:
higest_order_avg_size = df.groupby("Size")["Amount"].mean()

In [47]:
higest_order_avg_size.sort_values(ascending = False)

Size
4XL     783.259110
6XL     782.416436
5XL     775.146600
XS      630.345775
S       623.363205
3XL     618.810791
M       613.291945
L       599.058657
XL      598.164009
XXL     588.548654
Free    549.049656
Name: Amount, dtype: float64

In [48]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Qty',
       'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code',
       'ship-country', 'B2B'],
      dtype='object')

In [49]:
total_order = df["Status"].value_counts()

In [50]:
total_order

Status
Shipped                          77804
Shipped - Delivered to Buyer     28769
Cancelled                        18332
Shipped - Returned to Seller      1953
Shipped - Picked Up                973
Pending                            658
Pending - Waiting for Pick Up      281
Shipped - Returning to Seller      145
Shipped - Out for Delivery          35
Shipped - Rejected by Buyer         11
Shipping                             8
Shipped - Lost in Transit            5
Shipped - Damaged                    1
Name: count, dtype: int64

In [51]:
order_cancel_percentage = total_order["Cancelled"] * 100 / total_order.sum()

In [52]:
order_cancel_percentage

np.float64(14.213607288234154)

In [53]:
df.head()

,index,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Qty,currency,Amount,ship-city,ship-state,ship-postal-code,ship-country,B2B
0,0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,0,INR,647.62,MUMBAI,MAHARASHTRA,400081.0,IN,False
1,1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,1,INR,406.00,BENGALURU,KARNATAKA,560085.0,IN,False
2,2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,1,INR,329.00,NAVI MUMBAI,MAHARASHTRA,410210.0,IN,True
3,3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,0,INR,753.33,PUDUCHERRY,PUDUCHERRY,605008.0,IN,False
4,4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,1,INR,574.00,CHENNAI,TAMIL NADU,600073.0,IN,False

In [54]:
most_used_fullfillment = df["Fulfilment"].value_counts()

In [55]:
most_used_fullfillment

Fulfilment
Amazon      89698
Merchant    39277
Name: count, dtype: int64

In [56]:
df["ship-state"].value_counts()

ship-state
MAHARASHTRA           22260
KARNATAKA             17326
TAMIL NADU            11483
TELANGANA             11330
UTTAR PRADESH         10638
DELHI                  7048
KERALA                 6585
WEST BENGAL            5963
ANDHRA PRADESH         5430
GUJARAT                4489
HARYANA                4415
RAJASTHAN              2718
MADHYA PRADESH         2529
ODISHA                 2139
BIHAR                  2114
PUNJAB                 1919
ASSAM                  1663
UTTARAKHAND            1553
JHARKHAND              1456
GOA                    1137
CHHATTISGARH            909
HIMACHAL PRADESH        788
JAMMU & KASHMIR         702
PUDUCHERRY              351
CHANDIGARH              333
MANIPUR                 316
ANDAMAN & NICOBAR       257
MEGHALAYA               207
SIKKIM                  205
NAGALAND                185
TRIPURA                 151
ARUNACHAL PRADESH       146
MIZORAM                  76
DADRA AND NAGAR          70
LADAKH                   43
LAKSHADWEEP               4
NL                        2
APO                       1
AR                        1
Name: count, dtype: int64

In [57]:
df["Amount"].sum()

np.float64(78727101.3)

In [58]:
Revenue_contribution_by_category = df.groupby("Category")["Amount"].sum()

In [59]:
Revenue_contribution_by_category.sort_values(ascending = False)

Category
Set              39265172.03
kurta            21358246.70
Western Dress    11221355.69
Top               5353662.30
Ethnic Dress       791804.66
Blouse             460756.18
Bottom             151254.98
Saree              123933.76
Dupatta               915.00
Name: Amount, dtype: float64

In [60]:
total_cancel_order = df.query("Status == 'Cancelled'")

In [61]:
len(total_cancel_order)

18332

In [62]:
cancel_order_by_category = total_cancel_order.groupby("Category")["Category"].value_counts()

In [63]:
cancel_order_by_category

Category
Blouse            116
Bottom             60
Ethnic Dress      145
Saree              21
Set              7337
Top              1276
Western Dress    2122
kurta            7255
Name: count, dtype: int64

In [64]:
Cancellation_Rate_by_Category = cancel_order_by_category *100 / df["Category"].value_counts()

In [65]:
Cancellation_Rate_by_Category.sort_values(ascending=False)

Category
Set              14.591122
kurta            14.545783
Western Dress    13.690323
Bottom           13.636364
Saree            12.804878
Blouse           12.526998
Ethnic Dress     12.510785
Top              12.012804
Dupatta                NaN
Name: count, dtype: float64

In [66]:
Revenue_Lost_by_Category = total_cancel_order.groupby("Category")["Amount"].sum()

In [67]:
Revenue_Lost_by_Category

Category
Blouse             40019.18
Bottom             15214.98
Ethnic Dress       58473.66
Saree               9239.76
Set              3472451.03
Top               443726.30
Western Dress    1006482.69
kurta            1873676.70
Name: Amount, dtype: float64

In [68]:
df.columns

Index(['index', 'Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN', 'Qty',
       'currency', 'Amount', 'ship-city', 'ship-state', 'ship-postal-code',
       'ship-country', 'B2B'],
      dtype='object')

In [69]:
top_citiesby_revenue = df.groupby("ship-city")["Amount"].sum()

In [70]:
top_citiesby_revenue.sort_values(ascending=False)

ship-city
BENGALURU                               6850838.99
HYDERABAD                               4950141.82
MUMBAI                                  3709157.80
NEW DELHI                               3615635.78
CHENNAI                                 3103441.74
                                           ...
BAROH                                         0.00
bahadurgarh                                   0.00
Kanti Nagar extension, Krishna Nagar          0.00
Mira rd                                       0.00
Lapung.....Ranchi                             0.00
Name: Amount, Length: 8955, dtype: float64

In [71]:
averae_orderby_value = df["Amount"].mean()

In [72]:
averae_orderby_value

np.float64(610.4059026943206)

In [73]:
sample_data = df.head(1000)

In [74]:
sample_data.to_csv("sample_data.csv")

In [75]:
%history

import pandas as pd

df = pd.read_csv("Amazon Sale Report.csv")

df
df.shape
df.columns.tolist()
df.describe()
df.info()
df.isnull().sum()
df.drop(["promotion-ids","fulfilled-by","Unnamed: 22","Courier Status"], axis=1,inplace=True)
df
df.head()
df.duplicated().sum()
df["ship-state"] = df["ship-state"].str.upper()
df["ship-state"].value_counts()
state_mapping = {
    "RAJSHTHAN": "RAJASTHAN",
    "RAJSTHAN": "RAJASTHAN",
    "RJ": "RAJASTHAN",
    "ORISSA": "ODISHA",
    "PB": "PUNJAB",
    "NEW DELHI": "DELHI",
    "PONDICHERRY": "PUDUCHERRY",
    "PUNJAB/MOHALI/ZIRAKPUR": "PUNJAB"
}

df["ship-state"] = df["ship-state"].replace(state_mapping)
df["ship-state"].value_counts()
df[df["Amount"].isnull()]
(df["Amount"]==0).sum()
df[df["Amount"].isnull()]["Status"].value_counts()
cancel_null=df[(df["Amount"].isnull()) & (df["Status"] == "Cancelled")]
cancel_null
df.loc[cancel_null.index,"Amount"]=0
not_cancel_null=df[(df["Amount"].isnull()) & (df["Status"] != "Cancelled")]
not_cancel_null["Amount"]
median_amount = df["Amount"].median()
median_amount
df.loc[not_cancel_null.index,"Amount"]=median_amount
df["Amount"].isnull().sum()
df["Status"].value_counts()
df["Category"].value_counts()
df["ship-city"].value_counts()
higest_category_revenue = df.groupby("Category")["Amount"].sum()
higest_category_revenue.sort_values(ascending=False)
higest_state_revenue=df.groupby("ship-state")["Amount"].sum()
higest_state_revenue.sort_values(ascending=False)
average_by_category=df.groupby("Category")["Amount"].mean()
average_by_category.sort_values(ascending=False)
df["Date"] = pd.to_datetime(df["Date"])
monthly_sales = df.groupby(df["Date"].dt.strftime("%B"))["Amount"].sum()
monthly_sales.sort_values(ascending=False)
monthly_sales.sort_values()
revenue_overtime = df.groupby(df["Date"].dt.to_period("M"))["Amount"].sum()
revenue_overtime.sort_values()
df["Size"].value_counts()
df.columns.tolist
higest_revenue_size = df.groupby("Size")["Amount"].sum()
higest_revenue_size.sort_values(ascending = False)
higest_order_avg_size = df.groupby("Size")["Amount"].mean()
higest_order_avg_size.sort_values(ascending = False)
df.columns
total_order = df["Status"].value_counts()
total_order
order_cancel_percentage = total_order["Cancelled"] * 100 / total_order.sum()
order_cancel_percentage
df.head()
most_used_fullfillment = df["Fulfilment"].value_counts()
most_used_fullfillment
df["ship-state"].value_counts()
df["Amount"].sum()
Revenue_contribution_by_category = df.groupby("Category")["Amount"].sum()
Revenue_contribution_by_category.sort_values(ascending = False)
total_cancel_order = df.query("Status == 'Cancelled'")
len(total_cancel_order)
cancel_order_by_category = total_cancel_order.groupby("Category")["Category"].value_counts()
cancel_order_by_category
Cancellation_Rate_by_Category = cancel_order_by_category *100 / df["Category"].value_counts()
Cancellation_Rate_by_Category.sort_values(ascending=False)
Revenue_Lost_by_Category = total_cancel_order.groupby("Category")["Amount"].sum()
Revenue_Lost_by_Category
df.columns
top_citiesby_revenue = df.groupby("ship-city")["Amount"].sum()
top_citiesby_revenue.sort_values(ascending=False)
averae_orderby_value = df["Amount"].mean()
averae_orderby_value
sample_data = df.head(1000)
sample_data.to_csv("sample_data.csv")
%history

In [77]:
df.to_csv("final_amazonanalysis_clean.csv")